from dpymenus.settings import CONSTANTS_BUTTONS, CONSTANTS_CONFIRM, CONSTANTS_DENY, CONSTANTS_QUIT

CONFIRM = CONSTANTS_CONFIRM
DENY = CONSTANTS_DENY
QUIT = CONSTANTS_QUIT
GENERIC_BUTTONS = CONSTANTS_BUTTONS
