# 0 is no limit / disabled
HISTORY_CACHE_LIMIT = 10
SESSION_PER_CHANNEL_LIMIT = 1
SESSION_PER_GUILD_LIMIT = 3
SESSION_PER_USER_LIMIT = 10
SESSION_TIMEOUT = 3600

ALLOW_SESSION_RESTORE = False
HIDE_WARNINGS = False
